version: "3.9"

networks:
  webapp:

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - "./nginx:/etc/nginx/conf.d/"
      - "./../app:/app"
      - "./nginx/logs:/var/log/nginx"
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - webapp
  php:
    image: bitnami/php-fpm:8.1
    container_name: app
    hostname: mchs.loc
    volumes:
      - "./../app:/app"
    working_dir: "/app"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - webapp
  mysql:
    image: mysql:5.7
    container_name: db
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: mchs
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: dev
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - webapp
  mailhog:
    image: mailhog/mailhog
    container_name: mail
    logging:
      driver: 'none'
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      - webapp
